# -*- coding: utf-8 -*-
"""Class.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18QPlqLao2O-7tyzslBCCyo-SYaAwY7RS
"""

from MultipleFunctions import MultipleFunctions
#from filename import className

MultipleFunctions.percentage()
#className.FunctionName()

multipleFunctions.Subfields()
#className.FunctionName()

multipleFunctions.OddEven()
#className.FunctionName()

multipleFunctions.Eligible()
#className.FunctionName()

multipleFunctions.triangle()
#className.FunctionName()